site_name: Hissummer-mockserver
site_url: https://mockserver.hissummer.com
docs_dir: src
nav:
 - 主页: 'index.md'
 - 快速开始: 'quickstart.md'
 - 文档: 'documents/catalog.md'
 - 后端问题提交:  'https://github.com/hissummer-mockserver/mockServer/issues'
 - 前端问题提交: 'https://github.com/hissummer-mockserver/mockserverAdminUI/issues'
theme:
  name: mkdocs
  highlightjs: true
  include_sidebar: true
